### ISSUE TITLE
Error: 'HTimeseries' object has no attribute 'location'

### ISSUE THREAD

**Issue by aptiko** [openmeteo/hspatial#24]
```
Traceback (most recent call last):
  File "/opt/spatialize-venv/lib/python3.5/site-packages/hspatial/cli.py", line 40, in _execute_with_error_handling
    self._execute()
  File "/opt/spatialize-venv/lib/python3.5/site-packages/hspatial/cli.py", line 178, in _execute
    self.config.files, self.config.epsg, stations
  File "/opt/spatialize-venv/lib/python3.5/site-packages/hspatial/hspatial.py", line 86, in create_ogr_layer_from_timeseries
    point.AddPoint(ts.location["abscissa"], ts.location["ordinate"])
AttributeError: 'HTimeseries' object has no attribute 'location'
```

**Comment by aptiko** [comment]
Fixed in openmeteo/enhydris#265.
